### ISSUE TITLE
Why can't we upload a paper without filling "title, authors..."?

### ISSUE THREAD

**Issue by maxdan94** [kerzol/papers#6]
I think it would be faster to upload a paper without having to fill all the fields.
Also, it would be great if these fields can be modified afterward.

**Comment by kerzol** [comment]
In fresh version, these fields can be modified afterward.
But they are still required to fill. In the feature we could add a ml-algo that read, and extract this information from pdf.

**Comment by a3nm** [comment]
There are existing tools for the PDF extraction task, e.g., Grobid. But probably an easier option is to allow people to import papers from open-access repositories such as arXiv, HAL, or BASE: just specify the URL and the tool could retrieve both the paper and the structured metadata without any need for complicated ML. (Plus, hosting the papers on arXiv is probably a better idea anyway in terms of long-term preservation?)

PS: kudos on developing this interesting system!

**Comment by kerzol** [comment]
Yes for sure! It will be so cool to have a possibility to specify arxiv,
hal, doi, ... link.

Sergey

пт, 19 июн. 2020 г., 21:54 a3nm <notifications@github.com>:

**Comment by kerzol** [comment]
arXiv api is used now. I'll close this ticket. Open if any interest in other apis or methods of title/author extraction.
