### ISSUE TITLE
More space to "Edit your personal information"

### ISSUE THREAD

**Issue by maxdan94** [kerzol/papers#7]
So that I can add a schedule for the reading group. I would like to copy-paste this:
"""
WWW2017:
22/01/2018 The k-peak Decomposition: Mapping the Global Structure of Graphs
29/01/2018 ESCAPE: Efficiently Counting All 5-Vertex Subgraphs
05/02/2018 Linear Additive Markov Processes
12/02/2018 A Fast and Provable Method for Estimating Clique Counts Using Turán’s Theorem
19/02/2018 Indexing Public-Private Graphs
26/02/2018 Scalable Motif-aware Graph Clustering
05/03/2018 Correlation Clustering with Low-Rank Matrices
12/03/2018 When Hashes Met Wedges: A Distributed Algorithm for Finding High Similarity Vectors
19/03/2018 Submodular Optimization Over Sliding Windows
26/03/2018 AutoCyclone: Automatic Mining of Cyclic Online Activities with Robust Tensor Factorization
"""
and it doesnt work well

**Comment by kerzol** [comment]
yo @maxdan94 now u [can](https://papers-gamma.link/editinfo) add more text and format it using markdown + latex.
